### ISSUE TITLE
BUSM-596R: Business Spanish

### ISSUE THREAD

**Issue by megmcclell** [BYU-IS-Media/independent_study#105]
In the course catalog when you click on syllabus under this Business Spanish course, it says syllabus unavailable. I'm pretty sure it's because the syllabus is in Spanish labeled "Programa de Estudio"
![busm 596r-business spanish syllabus error](https://cloud.githubusercontent.com/assets/19712366/17347966/86683692-58d0-11e6-88a5-f4cef122aec0.PNG)

**Comment by megmcclell** [comment]
Luke confirmed that's the reason and that an active ticket is in with computer ops to fix it.

**Comment by TrevinAvery** [comment]
Syllabus is now up.
