### ISSUE TITLE
University Scholarship dates!? Old -> New!

### ISSUE THREAD

**Issue by luke80** [BYU-IS-Media/independent_study#107]
It currently has this:
![image](https://cloud.githubusercontent.com/assets/1438287/17375831/f7b6e312-596f-11e6-83b6-de1632906861.png)

We need the "Scholarship Application" paragraph to say (please edit out the passive voice, if possible - and remove the "contract language" feels):
Scholarships are awarded every month. Applications must be received (not postmarked) before the first day of the month in which they should be considered. Interested students may download an application here: https://is.byu.edu/site/financial/scholarshipapp.pdf

Do not enroll in a course until you have a scholarship. Enrollments begun prior to awarded scholarships are not elligable. Scholarship awards (or denial) will be sent by mail by the end of each month.

**Comment by tessakohler1** [comment]
Updated in Drupal.
