### ISSUE TITLE
Home Page: Click Here for More Info/Read More Links

### ISSUE THREAD

**Issue by megmcclell** [BYU-IS-Media/independent_study#11]
On the home page, I noticed two tabs are provided below the Teacher-led courses headline that take you to the same place. The links under Promotional material available are a little confusing and seem to kind of take you in circles, I'm also not sure what they're logging into or registering to post comments to: assuming new social media feature? Also, not sure if this part is final, but lots of the "read more" links take you to a page that really doesn't have any more information. Under We provide options heading the read more takes you to a new page with no new info and then you have to click on that page's link to take you somewhere. The We offer many benefits heading's read more link just says the same content. Let me know if any of this doesn't make sense!

**Comment by luke80** [comment]
Break these into two issues. You're on a good track, but you switched mid-stride. Let's fix each of these issues separately.

**Comment by tessakohler1** [comment]
We fixed the first part with the Teacher-led courses links. We're going to close this issue and open another one for the second part of the issue.
