### ISSUE TITLE
One Word Per Line

### ISSUE THREAD

**Issue by megmcclell** [BYU-IS-Media/independent_study#110]
I first noticed it when looking at the course catalog, but it's also in several other pages including:
Under the Courses Tab
*course catalog
*course policies
*Types of courses
*Purchase Orders

Under the Programs Tab
*High School Programs
![course catalog](https://cloud.githubusercontent.com/assets/19712366/17592660/5a8e5714-5fa0-11e6-89a9-c0fa3d87233a.PNG)

**Comment by luke80** [comment]
Fixed this early this morning. Thank you and happy Birthday!
