### ISSUE TITLE
Syllabus missing in Ninth grade English

### ISSUE THREAD

**Issue by TeriMartindale** [BYU-IS-Media/independent_study#113]
We received the information below on the Website survey on August 19.  

"The Syllabus for Ninth-Grade English isn't showing up."

The student didn't leave contact information. I am not sure if the student is referring to ENGL 041 or ENGL 043, or which section.

Thanks, Teri

**Comment by TrevinAvery** [comment]
All ninth grade English classes currently has a syllabus.
