### ISSUE TITLE
Server issues?

### ISSUE THREAD

**Issue by TeriMartindale** [BYU-IS-Media/independent_study#114]
The comment below was posted to the Website survey last night at 7:30. I don't have any additional information.

"My daughter is trying to retake a quiz in her ECON 041 online course, but your website appears to be stalled. We're trying to select the course, but only get a "Catalog data loading, please wait..." message. Are your servers down?? We're trying to retake this quiz before her high school classes begin (tomorrow). It seems we can't do this since your system is down or stalled."

Teri

**Comment by tessakohler1** [comment]
This doesn't seem to be an issue anymore.
