### ISSUE TITLE
'Click here to print' Formatting Issue (print not possible in some courses)

### ISSUE THREAD

**Issue by bmacosta** [BYU-IS-Media/independent_study#118]
One of my team members brought it to my attention that in the is.byu.edu course catalog, they navigated to the 'Syllabus' section of the SPAN-051-T002-002 course, and found that the 'Click here to print' element is not present. I opened the page source in Chrome, navigated down to the syllabus URL / object, clicked on the syllabus direct link within the source, and found that upon doing so, the syllabus opened in its own tab within the browser; in the far upper right corner, the 'Click here to print' link was present. In other words, it's probably still on the syllabus tab within each course in the catalog, but due to something formatting-related, it's not visible or clickable.

I've seen the issue in at least a couple other courses, e.g. ASL-041-T002-002, BCOM-041-T001, BCOM-041-S001, ACC-201-M001... It may be in many more, but definitely is not present in all (I just checked, and saw that for some courses, 'Click here to print' is still visible and works fine). I've also so far found no correlation (I've seen the issue with teacher-led courses, online courses, multiple subjects, both high school and university, etc). It's probably not related to that at all, but more pertaining to how much text is in a syllabus / where the text is...something along those lines, that's pushing the 'Click here to print' link out of visibility.

**Comment by luke80** [comment]
There is something complicated getting in the way here. I don't think we'll solve this issue, because it isn't wide-spread enough to make the required work worthwhile... sorry!
