### ISSUE TITLE
is.byu.edu - University Transcript Link concern

### ISSUE THREAD

**Issue by bmacosta** [BYU-IS-Media/independent_study#119]
One of my team members brought the following to my attention:

When navigating to is.byu.edu, 'Support Tab', then 'Order Transcript', and scrolling down to the 'University Transcripts' section, clicking on 'University Transcript Order Form' automatically directs students to a form typically found by going to transcripts.byu.edu, then clicking on 'Option 2: Order by Mail/Fax'. Here is the link:

https://registrar.byu.edu/sites/registrar.byu.edu/files/files/Transcript%20Request.pdf

This seems odd behavior (sending students on the transcript portion of the BYU IS website directly to the university mail / fax option). If we send them directly to a transcript option, it could be the online option instead, yes? 

https://y.byu.edu/ry/ae/prod/records/cgi/recStdTranRequestV2.cgi

Or perhaps better yet, we could have this link direct them to the main university transcript page (typically when I speak to university students on the phone, I just direct them to transcripts.byu.edu anyway:

'transcripts.byu.edu', or 'https://registrar.byu.edu/transcripts'

**Comment by bmacosta** [comment]
(as page is currently set up, students could potentially fill out the 'mail / fax' option after being sent directly there via link, only to find out later that the online option would have been available as well)

**Comment by tessakohler1** [comment]
Good point! I just updated the "University Transcript Order Form" link so it goes to the online option now. The link below it ("For more information on University Transcript click here") goes to the main university transcript page already, so I didn't change that one. So now both links are there!
