### ISSUE TITLE
Paper Course Links on Support tab 

### ISSUE THREAD

**Issue by ismstewart** [BYU-IS-Media/independent_study#127]
I know we are working on the Support page and there were somethings on the old page that we are not sure where the best place it will be to have them on the new page. The "withdraw request form," "submit assignment," and "print coversheet" are all used by people in our paper courses. Our paper courses are our least used enrollment so these actions don't need to be front and center but they need to be on the website somewhere. I know "the withdraw request form" has not been working so maybe we can get rid of that all together, but the other two need to be on the website. Could we maybe make a paper course resource page on the new Support tab and put these two options there?

**Comment by luke80** [comment]
Perhaps the links should get text indicating they are for paper courses?
Ala: "Paper course: Submit an Assignment"

**Comment by ismstewart** [comment]
I agree that it needs to clearly say these links are for paper courses. Sometimes students in the online courses try to use these forms and then they do it incorrectly.

**Comment by tessakohler1** [comment]
I added those three links to the general support section for now. We can put them somewhere else and/or change the title if we want to.

**Comment by ismstewart** [comment]
This is confusing if those links are on the general page. A lot of mistakes happen when the links are not clearly marked. Can you please add the Paper Course title on the general page before adding them?

**Comment by tessakohler1** [comment]
Right now they do say "Paper Course," as part of the title, so hopefully that makes sense for people.
