### ISSUE TITLE
Redundant Programs Info

### ISSUE THREAD

**Issue by megmcclell** [BYU-IS-Media/independent_study#13]
The Programs tab has the first section of info and then all of that is also repeated below the gray line again.

**Comment by luke80** [comment]
This is a bug in the drupal module, and will be fixed when we update next.

**Comment by tessakohler1** [comment]
Has this been updated yet?

**Comment by luke80** [comment]
It doesn't look like it. I'm really hoping it will be, but it should be done tomorrow...
