### ISSUE TITLE
Customers unable to log in.

### ISSUE THREAD

**Issue by TeriMartindale** [BYU-IS-Media/independent_study#130]
The two comments below were recorded on the Website survey yesterday afternoon. The issue may have been resolved, just letting you know. The customers didn't leave contact information.

"BYU's online education site wont allow me to log on. It says "The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.""

"I cannot log into my classes for some temporary unavailable service. I just want to do my school and I cant."

**Comment by luke80** [comment]
Yes, that was resolved yesterday. FYI it was load balance related.
