### ISSUE TITLE
Remove link to withdraw form under Support

### ISSUE THREAD

**Issue by TeriMartindale** [BYU-IS-Media/independent_study#133]
On the New support page, will you please remove the link at the bottom of the Enrollment/Withdrawal link under Support?  This is the link to remove: "Here is an online form you can fill out if you wish to request a withdrawal."

This link is in another place for students in paper courses. All other students should withdraw on the login page of their course.

Thanks, Teri

**Comment by tessakohler1** [comment]
The link is now removed.
