### ISSUE TITLE
No banner syllabus IS 110

### ISSUE THREAD

**Issue by ismstewart** [BYU-IS-Media/independent_study#136]
When you look up the syllabus on the website for IS 110 there is no banner picture just the placeholder image. Thanks

**Comment by tessakohler1** [comment]
This is a production issue in the course, so we can't fix it on our end.

**Comment by luke80** [comment]
Reported to corrections through CRM

**Comment by tessakohler1** [comment]
It looks like the placeholder image has been removed (there isn't any image at all now) so I'm going to go ahead and close this issue.
