### ISSUE TITLE
Enrollment/Withdrawal

### ISSUE THREAD

**Issue by kailah94** [BYU-IS-Media/independent_study#137]
On the Enrollment/Withdrawal page under courses and course policies, my trainee pointed out a discrepancy.  It explains that a refund/voucher is granted minus "withdraw fees."  However under the policy it states "Processing Fees."  It may be a little clearer if we use the same terminology- withdraw or processing fees.

**Comment by tessakohler1** [comment]
I added the word "processing," so now those places that just said "withdraw fees" now say "withdrawal processing fees." If you have a different thought about that, feel free to re-open the issue and we can change the wording again.
