### ISSUE TITLE
Support>Counselor>Check Student's Progress>Create a Secure Login

### ISSUE THREAD

**Issue by megmcclell** [BYU-IS-Media/independent_study#138]
Our counselor support team has received some calls from counselors saying they've clicked on Create a Secure Login and it takes them to a wrong page ("Who are you registering") and sometimes it goes to the correct page (Counselor Verification)...I have been able to replicate the correct response when I use Chrome, but when I tried Firefox and Microsoft Edge it took me to the wrong page. So possibly it's just a browser issue. Hoping you know how to fix this to be compatible with all browsers. Maybe there's more to it than this? :) 

I took screenshots of the correct page and the wrong page for reference:

***Correct***

![right](https://cloud.githubusercontent.com/assets/19712366/19291160/afbb5740-8fd0-11e6-8eba-1a71dab709ef.PNG)

***Wrong***

![wrong](https://cloud.githubusercontent.com/assets/19712366/19291167/c03bc2c6-8fd0-11e6-9ada-1185ba9002f4.PNG)

**Comment by tessakohler1** [comment]
Luke, do you know why the link would be behaving like this?

**Comment by aaronmoody** [comment]
I'm getting the wrong page when using Chrome in addition to Firefox and Edge.

**Comment by luke80** [comment]
This should now be working and is a Drupal webform!
https://is.byu.edu/secure/support/CounselorSupport/create-account
