### ISSUE TITLE
Materials Tab Formatting Errors 

### ISSUE THREAD

**Issue by gjacosta** [BYU-IS-Media/independent_study#14]
-No Separation of Cost and materials title
Price is right next to title of materials-makes it hard to read
ex. BIO 100
"Materials: 
Optional Materials
Bio 100 - Printed Course ReadingsPaper Manual$10.00"

-Also may have some courses with repeating or redundant material descriptions
ex. Chem 041 
Materials: 
Required Materials
Chem 041 - Multimedia CD: Virtual ChemLab and Periodic Table of Elements

Other Materials
$0.00
Optional Materials
Printed Course Readings
Paper Manual

$10.00

Required Materials
Chem 041 - Multimedia CD: Virtual ChemLab and Periodic Table of Elements

Other Materials
$0.00
Optional Materials
Printed Course Readings

Paper Manual

$10.00

Required Materials
Chem 041 - Multimedia CD: Virtual ChemLab and Periodic Table of Elements

Other Materials

$0.00

Optional Materials
Printed Course Readings
Paper Manual

$10.00

**Comment by luke80** [comment]
Fixed in theme, already released to computer operations for update... not sure why it's not there...
