### ISSUE TITLE
Change Address Form

### ISSUE THREAD

**Issue by msmith31** [BYU-IS-Media/independent_study#141]
May we add a link on the support/testing/proctor page that says "Address Change Form" and link it to the following link:

https://is.byu.edu/support/testing/proctor/change-address

**Comment by tessakohler1** [comment]
This has been added.

**Comment by msmith31** [comment]
Thank you so much, Tessa! Is there anyway to move the link to the bottom of the list right under the Proctor Certification link?

**Comment by tessakohler1** [comment]
Yep, it's moved to the bottom now!
