### ISSUE TITLE
Thanksgiving closure is not on the Website yet

### ISSUE THREAD

**Issue by TeriMartindale** [BYU-IS-Media/independent_study#147]
Will you please add Thanksgiving closures to the Website?  We will be closed Thursday and Friday, November 24 and 25.
Thanks, Teri

**Comment by tessakohler1** [comment]
I updated the information inside Drupal, so now @luke80 just needs to publish that article so it goes up on our home page (I don't have publishing rights, or else I would do it). It should hopefully be updated by tomorrow!

**Comment by tessakohler1** [comment]
Ok it's been updated!
