### ISSUE TITLE
BIOL-041 Error in Course Catalog

### ISSUE THREAD

**Issue by aaronmoody** [BYU-IS-Media/independent_study#148]
When trying to access BIOL-041 from the link to the online version in the course catalog, there is a "page not found" error.

https://is.byu.edu/description/BIOL-041-S002

**Comment by tessakohler1** [comment]
@luke80 do you know how to fix this? It looks like you can get to the course when you just search for the course in the drop-down menu, but not from the course catalog.

**Comment by luke80** [comment]
It was a failure in the auto-sync that's meant to run hourly
