### ISSUE TITLE
PHYSICS, PART 2: PHSCS 043 Course Catalog Broken Link

### ISSUE THREAD

**Issue by nrust6** [BYU-IS-Media/independent_study#149]
When trying to view PHSCS-043 Online course information from the High School Courses link, it displays "Page not found." Searching the course in the search box brings up the correct course information page.
https://is.byu.edu/description/PHSCS-043-S002 - broken link

**Comment by aaronmoody** [comment]
Multiple courses are having this problem.  I just opened a new issue listing this course along with several others.

**Comment by luke80** [comment]
Eighteen, in fact. Resolved now
