### ISSUE TITLE
Margins

### ISSUE THREAD

**Issue by bm218706** [BYU-IS-Media/independent_study#15]
This is just a suggestion, but I think that the margins on the page make it look weird. There is too much of the white in the margin and I think it would be more visually appealing if the tan border/outline was about 1/2 inch thicker.

**Comment by luke80** [comment]
An image would help. I'm not sure what tan border you're talking about.

The "too much of the white in the margin" is also unclear. Are you talking about the side margins, the margins above and below the text or margins between things?

**Comment by bm218706** [comment]
Sorry, I was thinking the side margins. this picture I labeled the tan and white parts. So make the tan part wider and bring in the white part closer to the writing on the page. Let me know if you need any further clarification.
![new website](https://cloud.githubusercontent.com/assets/19827518/15948592/ec309556-2e5e-11e6-8f01-054371f68764.JPG)

**Comment by luke80** [comment]
The layout of the entire site is probably going to change over time. We'll take your feedback into account when we work on those changes. For now, I'm closing this issue. (It's not gone, just closed)
