### ISSUE TITLE
SFL-260 Family Finance Course Information

### ISSUE THREAD

**Issue by nrust6** [BYU-IS-Media/independent_study#151]
https://is.byu.edu/description/SFL-260-M001

Textbook description tab says that no textbooks are required, but the course syllabus has required materials.

**Comment by luke80** [comment]
This is either an error in the master screen of Orion, or an error in the syllabus

**Comment by tessakohler1** [comment]
The textbooks tag shows required textbooks now, so I'm going to go ahead and close this issue.
