### ISSUE TITLE
Page Not Found Errors

### ISSUE THREAD

**Issue by aaronmoody** [BYU-IS-Media/independent_study#152]
Getting an error message "Page not found" when trying to view several courses from the course catalog.  It seems to be all the courses that were just activated on Friday 11/18 as part of the high school conversion project.  These courses are:

•	SOCSC-041-S002: Current Events (Online)
•	SELFG-051-S002: Leadership (Online)
•	HIST-065-S002: World History: Europe and Russia (Online)
•	SOCSC-051-S002: Sociology (Online)
•	GARD-041-S002: Home Gardening (Online)
•	AUTO-043-S002: Automotive Basics (Online)
•	FOODS-043-S003: Food and Nutrition, Part 2 (Online)
•	SWIM-043-S002: Intermediate Swimming (Online)
•	GSCI-031-S003: Seventh-Grade Science, Part 1 (Online)
•	HIST-066-S002: World Civilizations (Online)
•	FOODS-041-S003: Food and Nutrition, Part 1 (Online)
•	HIST-053-S002: Alaskan History (Online)
•	ALG-043-S002: Pre-Algebra, Part 2 (Online)
•	PHSCS-043-S002: Physics, Part 2 (Online)
•	ARAB-053-T002: Second-Year Arabic, Part 2 (TL)
•	RUSS-043-T002: First-Year Russian, Part 2 (TL)
•	LATIN-053-S001: Second-Year Latin, Part 2 (Online)
•	FREN-041-T002: First-Year French, Part 1 (TL)

**Comment by luke80** [comment]
I'll call this tentatively resolved. I'll verify the whole list tomorrow.

**Comment by tessakohler1** [comment]
These are all working in the course catalog now.
