### ISSUE TITLE
High School Scholarship Wording

### ISSUE THREAD

**Issue by megmcclell** [BYU-IS-Media/independent_study#153]
We received this in our suggestion box:

I noticed on the page on our website for the High School Scholarships, it says the following: 
   "Our new scholarship program benefits all middle and high school students. This scholarship program is now completely based on the student's financial need, academic achievement, and counselor recommendation. Only the high school counselor can recommend and apply for a student scholarship. We look forward to awarding more students with scholarships for online courses and providing our valued school counselors the ability to recommend students they feel are deserving. Only the high school counselor may recommend and submit an application for a student scholarship." The sentence about how only the high school counselor can submit the application is repeated twice. It seems really redundant! 

Thanks!

**Comment by tessakohler1** [comment]
I just went ahead and deleted that last sentence. If you want me to put it back in or change the wording any more, let me know! For now, I'm going to go ahead and close this issue.
