### ISSUE TITLE
Holiday closure - Website

### ISSUE THREAD

**Issue by TeriMartindale** [BYU-IS-Media/independent_study#158]
Hello,  do you mind removing the holiday closure information on the Website?

We will be closed Monday, January 16th for the Martin Luther King Jr. holiday, will you please add this information to the Website?

Thanks, Teri

**Comment by jvthomas93** [comment]
Hi Teri,

This has been completed - sorry for the delay! Please re-open this issue and let me know if there are any more changes you would like to see.
