### ISSUE TITLE
Delete Internet Explorer from technical requirements page

### ISSUE THREAD

**Issue by makeoni** [BYU-IS-Media/independent_study#159]
https://is.byu.edu/support/technicalreqs

Please remove 'Internet Explorer' from the list of recommended browsers pictured here: 

![capture](https://cloud.githubusercontent.com/assets/16021001/21815394/a8c9df20-d719-11e6-98ef-abe8b9f64c19.JPG)

**Comment by makeoni** [comment]
Also delete Internet Explorer further down on the page:

![image](https://cloud.githubusercontent.com/assets/16021001/21827054/303e6c82-d747-11e6-8722-1df37684cb13.png)

**Comment by jvthomas93** [comment]
Hi, @makeoni - this has been completed. Thanks!
