### ISSUE TITLE
Homepage Tabs Hover Info-Minor

### ISSUE THREAD

**Issue by gjacosta** [BYU-IS-Media/independent_study#16]
This is a minor thing, but I think it was a little easier to use the site when hovering over a tab on the home page would open up the options/information under that tab, instead of having to click to open each tab. The tabs I'm talking about are the Courses, About, Programs, etc. and Students, Parents, Educators tabs.

**Comment by luke80** [comment]
1) Hover isn't mobile friendly. Newer iPhones have a form of this, but it isn't reliable.
2) I want to know how useful the menus are, and tracking clicks on them is impossible if you don't require a click (and I don't want spam from hundreds of "hover" events).
3) There are too many menus. Making it easier for people to find what they want my quieting down the pain of scanning multiple menus is a good idea. However, the longer-term solution is to eliminate the extra menu options and make it easier to find what you're looking for by only showing what people are actually looking for. Simpler.

I'm not planning on changing this immediately, but I'm open to discussing it. What do you think of my 3 reasons?

**Comment by gjacosta** [comment]
Those are all good reasons-I could definitely see the hover option being problematic on older phones, tracking clicks impossible, and people feeling like there are too many menus (clutter). I think you're right--click tabs will ultimately work better

**Comment by luke80** [comment]
I'm glad you agree. However, I appreciate your feedback. I'm still open to talking about it, but I'm closing the issue.
