### ISSUE TITLE
UC-approved link

### ISSUE THREAD

**Issue by gjacosta** [BYU-IS-Media/independent_study#17]
This used to be an issue the current website too (looks like it was changed to the correct link recently). Could I suggest changing the link under the UC-approved course list to:
https://hs-articulation.ucop.edu/agcourselist#/list/details/4241/

The link on the new site takes students to a general part of the UC site and it could be hard to navigate to our UC-approved courses from there.

**Comment by tessakohler1** [comment]
Fixed in Drupal.
