### ISSUE TITLE
Cart Icon Stays Visible with Menus over

### ISSUE THREAD

**Issue by gjacosta** [BYU-IS-Media/independent_study#18]
When clicking on the Parents or Educators tabs, the cart icon is still visible when the drop-down menus appear. It doesn't really impact the Parents drop-down menu but it does partially cover the first link under the Educators tab.

**Comment by tessakohler1** [comment]
Where are we at on this, Luke?

**Comment by luke80** [comment]
Fixed in the theme, not yet sent to computer operations for release to site

**Comment by luke80** [comment]
Updated in live site!
