### ISSUE TITLE
About Page

### ISSUE THREAD

**Issue by jvthomas93** [BYU-IS-Media/independent_study#19]
The [current ](http://is.byu.edu/site/about/what-is.cfm)about page reads differently. It contains this, which the drupal version does not: 

"We have many pricing options to assist you. Please learn about them by touching here.

We also have our "Best Value" options for you here."

The drupal version has a paragraph that is not included in the current version, which the above text replaced. 

Also, why does it read "touching here?" That seems weird.

**Comment by tessakohler1** [comment]
Fixed in Drupal. We ignored the strange wording in the current site.
