### ISSUE TITLE
Cost of Quarter Credit Courses

### ISSUE THREAD

**Issue by jvthomas93** [BYU-IS-Media/independent_study#20]
On one page (Quarter Credit Courses) it says $84, but on another $92. Which is it?

**Comment by megmcclell** [comment]
They are $92

**Comment by tessakohler1** [comment]
It looks like SELFG 051 is still listed as $84 on our current website. Is that wrong then?

**Comment by megmcclell** [comment]
That's weird. When I click on the link through the Quarter Credit Courses page, it says $84, but when I go straight through the course catalog or quick search it says $92. $92 is the correct price.

**Comment by tessakohler1** [comment]
It looks like SLFG 051 is linked to a paper version of the course that is still listed as $84. So even that paper version should be $92?

**Comment by luke80** [comment]
This is probably a good time for Dan to be aware of the issues, as he can help you resolve them. Yes, I believe all the paper courses should be the $92, but Dan's the man for this question.

**Comment by dmennear** [comment]
The quarter credit courses are currently $92.  All $84 prices should be changed to $92.

**Comment by tessakohler1** [comment]
Waiting for Sara to change the course price in Orion.

**Comment by dmennear** [comment]
This is fixed. closing issue
