### ISSUE TITLE
FAQ Pages

### ISSUE THREAD

**Issue by jvthomas93** [BYU-IS-Media/independent_study#23]
The "General FAQ" page in Drupal is pretty messy - super long and hard to navigate. There's also no media on the page, just text, which isn't good for SEO. This isn't urgent, but needs to be cleaned up. 

The same problem exists for "Counselor FAQs"

**Comment by jvthomas93** [comment]
Luke, with the lengthy process to complete this, I'm not sure that I will be able to complete it this week with school starting and other things.

**Comment by luke80** [comment]
This is very important, but also needs to involve many people. This page will be addressed in line after others. For now I'm closing this issue. Enhancements that are closed are not forgotten, but are currently waylaid
