### ISSUE TITLE
Missing Pages

### ISSUE THREAD

**Issue by jvthomas93** [BYU-IS-Media/independent_study#24]
Currently missing:
Tutorials
ACT and College Prep Camps
Check Student's Progress

Also, most of the forms under the "Courses" menu redirect to the old site.

**Comment by tessakohler1** [comment]
Check Student's Progress and Tutorials are missing under the "Support" section. Don't worry about ACT and College Prep Camps.

**Comment by luke80** [comment]
Check progress is still on isreg, the other is using isreg content inside a drupal article.
