### ISSUE TITLE
Messy Pages

### ISSUE THREAD

**Issue by jvthomas93** [BYU-IS-Media/independent_study#25]
These pages are either confusing, don't display information in a intuitive way, or have confusing structures:

- Technical Support Page (very diff. than old site)

- Free Tutoring Page (confusing)

- Counselor Contact (bad info structure)

- Contact Us Menu - confusing because somethings link to the same thing.

**Comment by luke80** [comment]
great feedback. Please break these apart so that we can resolve them appropriately and one at a time.
