### ISSUE TITLE
Logo in Header of Website

### ISSUE THREAD

**Issue by douggw** [BYU-IS-Media/independent_study#28]
There is no Independent Study logo in the header, like there is now. It's just plain (boring) text.

New:
![image](https://cloud.githubusercontent.com/assets/19956401/16092882/d7379edc-32f6-11e6-8fb8-b3ca7521a4a8.png)

Old:
![image](https://cloud.githubusercontent.com/assets/19956401/16092904/e851c878-32f6-11e6-8c7e-2a5fabd1bd1b.png)

**Comment by luke80** [comment]
Yes, this is important to have before the site goes live... I'll get it in the next code update.

**Comment by luke80** [comment]
Updated in theme, not yet sent to computer operations for release to the site.

**Comment by luke80** [comment]
Updated in live site!
