### ISSUE TITLE
Best Value Courses

### ISSUE THREAD

**Issue by megmcclell** [BYU-IS-Media/independent_study#29]
This is on the current website too. The paragraphs have multiple varying prices. 1st paragraph says starting at the low price of $49. Then just two lines below it says: Also, these courses now cost $50. Then when you click on all the links they actually all cost $52. So we should just put that consistent price instead.

**Comment by tessakohler1** [comment]
I just updated it to $52 on the Drupal site a little while ago, so it should be good now.

**Comment by megmcclell** [comment]
Yeah sorry! Right after I wrote this I realized I had somehow linked back to our current site instead of the Drupal site. I did notice though that when you click on these course links it doesn't show the price in the top right corner, it says "How to avoid additional costs" and that link takes you to a Page not found location.

**Comment by tessakohler1** [comment]
Luke, what is the purpose of the "How to avoid additional costs"? It doesn't link to a working page right now. Is this something we can remove in order to go live?
