### ISSUE TITLE
Programs not aligned

### ISSUE THREAD

**Issue by douggw** [BYU-IS-Media/independent_study#30]
Click on the Programs Tab > in the bottom section, the titles that don't fit are not aligned when they wrap. They wrap all the way to the left and are not indented and it looks funny. In the old site, they wrap correctly - indented properly.

![image](https://cloud.githubusercontent.com/assets/19956401/16093139/eb4229aa-32f7-11e6-8482-78dd849c1882.png)

**Comment by tessakohler1** [comment]
The site is intentionally written right now to be formatted for mobile, so it'll be taken care of later.
