### ISSUE TITLE
Programs spaced too far apart

### ISSUE THREAD

**Issue by douggw** [BYU-IS-Media/independent_study#31]
Click on Programs > the programs listed are vertically spaced too far apart.  This causes Bachelor of General Studies to not fit in the list.  In the old version of the website, all these were closer together and it looked much cleaner and easier to read. The new way is more difficult to read.

![image](https://cloud.githubusercontent.com/assets/19956401/16093270/69973250-32f8-11e6-802e-c12d9138cf34.png)

**Comment by luke80** [comment]
resolved!
