### ISSUE TITLE
Courses Tab - Information too long

### ISSUE THREAD

**Issue by douggw** [BYU-IS-Media/independent_study#38]
Click on Courses tab and the information presented is so long, you have to scroll to see it all.  The items are spaced too far apart vertically.  In the older version, they were much more succinct and much easier to read.

![image](https://cloud.githubusercontent.com/assets/19956401/16093757/8e7ce8a6-32fa-11e6-9a20-6c290bbf629a.png)

**Comment by luke80** [comment]
The menus are ... trouble. Our top priority for release is mobile. We aren't going to hit it perfectly, and the main reason is our menus. There will be significant work done on them soon, but it may have to wait until after the site is live.

**Comment by luke80** [comment]
Resolved!
