### ISSUE TITLE
UC Courses link to old catalog with different logo

### ISSUE THREAD

**Issue by douggw** [BYU-IS-Media/independent_study#39]
All the UC Courses link to the catalog showing the old (but better) header Independent Study logo.  Logo's are not consistent.

![image](https://cloud.githubusercontent.com/assets/19956401/16093845/d3fd1bda-32fa-11e6-8a20-c2317ed99db2.png)

**Comment by luke80** [comment]
The links on this page are all pointing to the is.byu.edu URL. This won't be much of a problem when we "go live", but until then it works weirdly.

Can someone go in and remove the hostname from the links, please?

**Comment by tessakohler1** [comment]
Fixed.
