### ISSUE TITLE
Courses information not indented properly

### ISSUE THREAD

**Issue by douggw** [BYU-IS-Media/independent_study#40]
Click on Courses - those items that wrap don't indent enough and are difficult to read.  In the old version, they are spaced to not wrap which makes it aligned and pleasing to the eye. 

![image](https://cloud.githubusercontent.com/assets/19956401/16093911/0f24d086-32fb-11e6-9373-fb5c89b0b296.png)

**Comment by luke80** [comment]
Yes, the menus are ugly. This is, sadly, lower priority than content fixes.

**Comment by luke80** [comment]
Resolved...
