### ISSUE TITLE
Twitter link in Footer is broken

### ISSUE THREAD

**Issue by douggw** [BYU-IS-Media/independent_study#42]
In the Follow section of the footer, the link to Twitter is broken.
![image](https://cloud.githubusercontent.com/assets/19956401/16094238/90e99934-32fc-11e6-9e29-b5b5c56e9973.png)

![image](https://cloud.githubusercontent.com/assets/19956401/16094247/9925bd3a-32fc-11e6-8ca4-2eefe5af956d.png)

**Comment by tessakohler1** [comment]
Fixed in Drupal.

**Comment by luke80** [comment]
I doubt this is fixed.
![image](https://cloud.githubusercontent.com/assets/1438287/16198666/e84a4e2e-36c3-11e6-81f7-e433e6e04965.png)

this ought to be the public URL for our twitter... not a "currently reading" link

**Comment by tessakohler1** [comment]
The link under "Follow" was broken and I fixed it to take people to our Twitter page (this was the issue Doug was talking about). The link under "Share" pulls up that page in your screenshot, which I think it's supposed to do.
