### ISSUE TITLE
Google link in Share footer is broken

### ISSUE THREAD

**Issue by douggw** [BYU-IS-Media/independent_study#43]
In the Share section of the footer, the link to google plus is broken.
![image](https://cloud.githubusercontent.com/assets/19956401/16094291/c972bf06-32fc-11e6-9da3-d42015d1289c.png)

![image](https://cloud.githubusercontent.com/assets/19956401/16094299/d3665dce-32fc-11e6-9e90-05fd09af7612.png)

**Comment by tessakohler1** [comment]
Removed google+ link.
