### ISSUE TITLE
Additional Costs broken link

### ISSUE THREAD

**Issue by douggw** [BYU-IS-Media/independent_study#44]
Go to any Course in the catalog, and then click on "How To Avoid Additional Costs" and the link is broken.

![image](https://cloud.githubusercontent.com/assets/19956401/16094677/91b0d344-32fe-11e6-975d-4d2aa1f01553.png)

**Comment by tessakohler1** [comment]
This page will be added before the site goes live.

**Comment by luke80** [comment]
Removed from theme files. Will disappear when updated
