### ISSUE TITLE
Pop up in Catalog covers link

### ISSUE THREAD

**Issue by douggw** [BYU-IS-Media/independent_study#45]
In the catalog, each course has a link below the description to what kind of course it is: Paper, Online, etc.  When you hover over the type of course, the pop up box and explains the course, covers up the link.  You can still click on the text in the pop-up box, but it looks funny that the link is covered up.  Especially when there are more than one type of course.  For example, when there is a Paper and Online version of the course, the pop up hides the Paper link.

![image](https://cloud.githubusercontent.com/assets/19956401/16094841/44d42b10-32ff-11e6-83cc-9398481b2d07.png)

**Comment by luke80** [comment]
Agreed. Removed the "hover" trash.
