### ISSUE TITLE
Petitions Process correction (Students tab-Course Policies-Petitions Process- How decisions are made)

### ISSUE THREAD

**Issue by TeriMartindale** [BYU-IS-Media/independent_study#48]
Please change the sentence in yellow (screen shot) to the sentence below:
Students are notified of committee decisions in an email to the address provided by the student on the appeals form

![petitions](https://cloud.githubusercontent.com/assets/19712633/16156218/660a1426-3470-11e6-9e94-e7ba5e9dbf23.PNG)

**Comment by tessakohler1** [comment]
Updated in Drupal.
