### ISSUE TITLE
Contact Us Tab - Counselors page (format, add/delete marketers...)

### ISSUE THREAD

**Issue by TeriMartindale** [BYU-IS-Media/independent_study#49]
- It would be nice if this page was formatted more closely to the current Web page, The Drupal page has one long single line of information to scroll through.

- Photos and contact information: Ben Watson and Chad Tolman should be removed. Trent McCall, David Hoffman and Michelle Smith should be added.

- The current page has "Educator Contact Information" at the top. The drupal page has "Counselor Contact Information" at the top. I believe Marketing prefers "Educator"

- Is the list of states under each Marketer current?

Thanks.

**Comment by luke80** [comment]
This page is in dire need of update. The content is very old. The design issues can be resolved later, but the content needs to be fixed asap.

**Comment by tessakohler1** [comment]
I updated the information, and I'm just working on finding the updated photos now.

**Comment by tessakohler1** [comment]
Photos are updated.
