### ISSUE TITLE
Course Catalog Search Icon

### ISSUE THREAD

**Issue by gjacosta** [BYU-IS-Media/independent_study#50]
Under the Course Catalog search bar, there is a magnifying glass image that appears to be a clickable, but doesn't seem to do anything when clicked. Maybe it is there to engage the search results, but it seems unnecessary since the search automatically starts searching after typing in text.
 
It might be cleaner to have the magnifying glass image:
-Be a clickable that opens the search bar 
-Be an image only (for aesthetic appeal?) but don't let it look clickable when hovering over and place to side of search bar rather than underneath
-Or get rid of magnifying glass image

**Comment by luke80** [comment]
Resolved in other repo; commit 3ea09a3
