### ISSUE TITLE
Paper courses on the main page

### ISSUE THREAD

**Issue by evecd** [BYU-IS-Media/independent_study#54]
There's no description of paper courses on the main page.

**Comment by luke80** [comment]
Which main page? The catalog?

**Comment by evecd** [comment]
On this main page: http://indstudy.ce.byu.edu/

**Comment by luke80** [comment]
Yes, now I see.
![image](https://cloud.githubusercontent.com/assets/1438287/16198845/a555f388-36c4-11e6-9a6f-c0d5cc12e598.png)

This is a "teaser" fix. Can someone please update the teaser version of this to be better, or perhaps we should make the view show all contents and not truncate?

**Comment by bekahml** [comment]
I fixed it!... With lots of help from Luke!
