### ISSUE TITLE
High School Scholarship information

### ISSUE THREAD

**Issue by bm218706** [BYU-IS-Media/independent_study#57]
On the high school scholarship page under "What is the criteria to receive a scholarship?" it says "Schools will need one previous enrollment with BYU Independent Study to be eligible to apply for a course scholarship for a student." I think that it would be helpful to include that schools need one previous enrollment **In the past year** to be eligible to apply for a scholarship.

**Comment by tessakohler1** [comment]
Fixed in Drupal.
