### ISSUE TITLE
Remove Newsletter Sign Up page (Educator tab)

### ISSUE THREAD

**Issue by TeriMartindale** [BYU-IS-Media/independent_study#58]
Marketing no longer sends a newsletter to educators, so the newsletter information can be deleted. This page is on the Educators tab--Newsletter Sign Up.

Will you also remove "Newlsetter Sign up" on the About tab?

![newsletter](https://cloud.githubusercontent.com/assets/19712633/16165216/f1454d74-349f-11e6-860c-56acb39f6d2f.PNG)

Thanks.

**Comment by luke80** [comment]
It's turned off for now. We may revisit this soon. There is a need for more active contact with people, but a better way should be discussed/implemented. :)
