### ISSUE TITLE
Update graduation deadlines in FAQ (Under "How much time do I have to complete my course?)

### ISSUE THREAD

**Issue by TeriMartindale** [BYU-IS-Media/independent_study#59]
Will you please replace the current deadlines under "University Courses" with the table below? (General FAQ tab--"How much time do I have to complete my course?--University Courses

![deadlines](https://cloud.githubusercontent.com/assets/19712633/16164401/2ceb0cf6-349b-11e6-893e-7e5728d58d84.PNG)

**Comment by tessakohler1** [comment]
Updated in Drupal.
