### ISSUE TITLE
Redundant Course Catalog Info

### ISSUE THREAD

**Issue by megmcclell** [BYU-IS-Media/independent_study#6]
I'm not sure if this was intentional, but it seems redundant to have the Course Catalog in both the top section of the Courses tab as well as below the gray line with the course policies, tuition, withdrawal request form, etc...Thanks!

**Comment by dastrup** [comment]
There seems to be a problem with the importer, Luke s working on it.

**Comment by luke80** [comment]
Fixed in new release, waiting for Computer Operations to update the files.
