### ISSUE TITLE
BYU Bookstore name change to BYU Store

### ISSUE THREAD

**Issue by TeriMartindale** [BYU-IS-Media/independent_study#60]
Can you correct this on the FAQ page?  **The new name is BYU Store and the URL is www.byustore.com/.** 
(FAQ--Where can I buy my Textbooks?--BYU Bookstore Buyback Policy, Ordering books)

![byu store](https://cloud.githubusercontent.com/assets/19712633/16164886/d1f42d3e-349d-11e6-83bd-2deaa0e577ab.PNG)

Will you also change this on the PO FAQ and the PO Policies page?

![po faq](https://cloud.githubusercontent.com/assets/19712633/16165002/9d3a4f32-349e-11e6-8ac0-c2e361a900e9.PNG)

Will you also change it on the Music 101 page?

![music - byu store](https://cloud.githubusercontent.com/assets/19712633/16165098/2faa8e2c-349f-11e6-922e-eabaaf52df8b.PNG)

**Comment by tessakohler1** [comment]
I changed it in all the locations except for Music 101. When I go in to edit it in Music 101, it asks for a feed url in order to save the changes to the description text, and I don't know what that would be.

**Comment by luke80** [comment]
This change needs to be made in Orion. Ask Dan to correct it, and you can close this issue.

**Comment by dmennear** [comment]
I fixed it in Orion.  This issue should be completed now.
