### ISSUE TITLE
Balloon Boy commercial

### ISSUE THREAD

**Issue by TeriMartindale** [BYU-IS-Media/independent_study#61]
Is there a reason the balloon boy commercial is missing on the Commercials page under the About tab?  (that one is my favorite of the three :))

Thanks.

**Comment by tessakohler1** [comment]
I think it's still there! :) Or at least I can see it when I look at the page...

**Comment by luke80** [comment]
The iframe "src" was specifying a protocol. In normal English; The location for the video was specifically http, and it needed to not say that. I took out the http: at the beginning so that it will use whatever the page uses.
