### ISSUE TITLE
Course Catalog Subject Error

### ISSUE THREAD

**Issue by gjacosta** [BYU-IS-Media/independent_study#63]
The Course Catalog Subject box on the old site lets you choose which subject to search. The new website Subject Box does not let you select any subjects and is set to "All" only

**Comment by luke80** [comment]
Is this a speed problem? When I try, I get a long list of subjects, but it takes too long. Are you not waiting? Screenshot would help a lot.

**Comment by gjacosta** [comment]
This is actually working just fine for me now-on Friday when testing I wonder if I just wasn't waiting long enough for the subject list results (as you suggested) or maybe I had unchecked all course versions (teacher-led, online, paper) when testing the search and forgot to check a box again before trying the subject list.

**Comment by luke80** [comment]
Great! Then, until this crops up again I'm closing this issue. The catalog listing page is an interim solution until we have a truly drupal-native catalog page ready. This will make lots of things better!
