### ISSUE TITLE
BYU Online info

### ISSUE THREAD

**Issue by TeriMartindale** [BYU-IS-Media/independent_study#64]
Dan, 

This is about the live Website, not the Drupal Webite. The Tuition and Fees page has the BYU Online classes titled as "BYU Online Semester Classes". (Parents tab--About Us--Tuition and Fees) This sounds a little like the BYU Semester soon to come. Can you change this to "BYU Online Classes"? As far as I understand the title for the two different offerings is BYU Online and BYU Semester and the current title combines both.

![byu online](https://cloud.githubusercontent.com/assets/19712633/16199649/a6116ab6-36c7-11e6-9209-c27792e3c081.PNG)

Thanks.

**Comment by tessakohler1** [comment]
Fixed in Drupal.
