### ISSUE TITLE
Home page

### ISSUE THREAD

**Issue by TeriMartindale** [BYU-IS-Media/independent_study#68]
- Are you matching the Drupal page to the current Website home page when you make Drupal live?  I just want to make sure the information about updated business hours is not included under "News". It was removed from the home page some time ago.

- If Drupal goes live the last week of June, will you please include the July 4th closure information  under "News"? (We will be closed Monday, July 4th, due to the Fourth of July holiday.) We will also be closed Monday, July 25th due to the Pioneer Day state holiday and it would be nice to add that as well.

Thank you.

**Comment by tessakohler1** [comment]
I matched the information in the "News" section, and I also included the holiday closure information. The two pages should match now.
