### ISSUE TITLE
Courses Tab Drop-Down Menu Link Issues

### ISSUE THREAD

**Issue by gjacosta** [BYU-IS-Media/independent_study#70]
When clicking the Courses tab on the Home Page, then either the High School courses, Middle School courses, or Continuing Education courses link from the drop-down menu, the check box for the appropriate course type doesn't automatically check. So, it looks like there are No Results Found when trying to search for those course types from the drop-down menu links (though once someone is in the course catalog, if they then click the check box they can see the courses normally). 

The University courses link automatically checks the university course box when clicked on from the Courses tab so that results come up immediately-should be like this for other course categories too.

Free courses link from the Courses drop-down menu appears to be broken.

**Comment by tessakohler1** [comment]
This is fixed in the new live version of the site.
