### ISSUE TITLE
FAQ Transcript Information

### ISSUE THREAD

**Issue by bm218706** [BYU-IS-Media/independent_study#75]
In the FAQ page the information about university vs hs transcripts is switched. the transcript fees says that the information is listed University Courses / High School and Middle School Courses, but all the actual fees listed below are listed High School and Middle School Courses/University Courses.

![image](https://cloud.githubusercontent.com/assets/19827518/16388913/ac1705c4-3c58-11e6-927f-e9ac148d84ca.png)

**Comment by tessakohler1** [comment]
Fixed in Drupal.
