### ISSUE TITLE
Submitting University Transcripts broken link

### ISSUE THREAD

**Issue by bm218706** [BYU-IS-Media/independent_study#76]
In the FAQ, under "submitting university course transcript request" there is a link to the online form. The link to this form does not work. When you click on it, it says that the page is not found. 

Also under this section it says that these transcript requests can only be submitted through a fax, mail, or in person. The forms can be submitted online through the BYU records office and the records office actually told us that they prefer that students submit their university transcripts online.

**Comment by luke80** [comment]
Changed the link (again) and removed the unwanted request methods!
