### ISSUE TITLE
Links to is.reg in Courses tab

### ISSUE THREAD

**Issue by gjacosta** [BYU-IS-Media/independent_study#77]
Not sure if this was an issue or not (site designed to do this?) but I noticed some of the links under the Courses tab take you to is.reg.byu.edu and then if students click the home page button there they will stay on is.reg.byu.edu instead of going to indstudy.ce

Links that do this include:
Withdraw Request Form, Submit Assignment, Print Cover Sheet, Find Testing Center, Request Catalog, and Courses Preview Request

Also under the Support tab:
Submit Assignment

**Comment by bmacosta** [comment]
also occurring under 'Free Courses' link (returning 'about:blank' in the URL field instead of website link, and directs to a blank page)

**Comment by luke80** [comment]
The "Free Courses" link issue needs to be submitted separately. We need to fix that issue, and closing this issue will cause it to be lost. I'll submit it on your behalf. The isreg.byu.edu links are deliberate. Those resources are only available at that server currently and therefore are correct.
