### ISSUE TITLE
Feedback/Complaint Survey is missing at the bottom of the page

### ISSUE THREAD

**Issue by TeriMartindale** [BYU-IS-Media/independent_study#78]
Can you add the information below (see yellow highlight on screen shot) to the Drupal Website? Currently there is a Website Survey but the complaint/feedback survey is missing. 
Thanks.

![survey](https://cloud.githubusercontent.com/assets/19712633/16421620/e1e5501a-3d12-11e6-8592-5f50b0012685.PNG)

**Comment by luke80** [comment]
Fixed!
