### ISSUE TITLE
New Teacher-Led Courses/Types of Courses

### ISSUE THREAD

**Issue by megmcclell** [BYU-IS-Media/independent_study#81]
I have trouble with the wording on this page found through the "read more" link under the New Teacher-Led Courses, also found by going through types of courses:

http://indstudy.ce.byu.edu/site/about/coursetypes/tl.cfm

The bottom portion makes it sound like the online is better than TL because it's cheaper and still engaging and interactive...also misleading since so many of our TL courses are now no longer offered in an online version. Maybe we can brainstorm better wording? Below is the current wording:

Other Course Options:

If you are looking for a less expensive online course that is still engaging and interactive, you probably want the Online course.
If you are looking for a course that does not require online access and provides a printed course packet that includes all course materials (syllabus, course readings, non-graded self-check assignments, and computer-graded Speedback assignments with bubble sheets) you probably want the Paper course.

I think the most clear description of our types of courses was from the table from the old site:
http://is.byu.edu/site/about/coursetypes/index.cfm

![types of courses descriptions](https://cloud.githubusercontent.com/assets/19712366/16428155/d6aec42c-3d2d-11e6-861a-b318e443ae8d.PNG)

I noticed this table is missing in the Drupal site and the "New Teacher-Led courses is bad wording for this place. This is getting long...and potentially multiple issues. Let me know what you think?

**Comment by luke80** [comment]
Yes, there are issues with how complicatedly we describe our course types and things.

Unfortunately, relying on tables won't work as well for mobile. You may have noticed that information presented in this way is becoming less common on the internets...

There will be a much larger and fuller conversation about this page shortly.
