### ISSUE TITLE
Site Object Formatting Issue

### ISSUE THREAD

**Issue by bmacosta** [BYU-IS-Media/independent_study#82]
On Drupal site, if page zoom level is made less than the standard 100, the prominent blue 'Apply Now for ACT and College Prep Camp' object becomes obscured, and the text info immediately below is forced downward and put out of its correct space (this formatting behavior not present in pre-Drupal site).

**Comment by luke80** [comment]
So cool! you found this error faster than we did and correctly identified what causes it! Thank you.

**Comment by luke80** [comment]
This has been repaired in the code and will be fixed in next release
