### ISSUE TITLE
Contact Us Tab

### ISSUE THREAD

**Issue by megmcclell** [BYU-IS-Media/independent_study#89]
This tab needs some work to me. The paragraph under customer support says "Or call us", but doesn't mention chat or anything beforehand that would require an "or" statement. Even on the tech support one where it mentions chat first, it shouldn't be a period and then a new sentence starting with Or call us. So for right now I think this needs to be fixed:
![contact us](https://cloud.githubusercontent.com/assets/19712366/16499411/9d047582-3ebd-11e6-82be-6bf6423e15ab.PNG)

Other Feedback/Ideas about this tab for potential additional changes:
If you click on anything (excluding Counselors) under this tab it take you to the same page with the customer supp, tech supp, & tutors info so it seems like we could just maybe make it more efficient by having all the info just on that first part or under support and then the counselor support line listed on the counselor support page that has been talked about being created? I'm not sure what all exactly needs to happen. Let me know if you want to discuss ideas. There's lot of empty space as is and it's not being used effectively in my opinion.

**Comment by luke80** [comment]
Those paragraphs are not able to be formatted much. Paragraphs and such are not possible.
