### ISSUE TITLE
University Transcript Bad Links

### ISSUE THREAD

**Issue by mcshinsky90** [BYU-IS-Media/independent_study#90]
Both of the links for the university transcripts are bad links. 
![12](https://cloud.githubusercontent.com/assets/20323154/16624786/52cbf71e-435f-11e6-89fa-90b69575ddce.PNG)
![13](https://cloud.githubusercontent.com/assets/20323154/16624787/52cc58b2-435f-11e6-9305-ab1840562a78.PNG)

**Comment by tessakohler1** [comment]
Fixed in Drupal.
