### ISSUE TITLE
Options not working the first time under courses tab

### ISSUE THREAD

**Issue by mcshinsky90** [BYU-IS-Media/independent_study#91]
When selecting some options under the tabs they don't direct you to the right places the first time you select them. The second time you select them they do. 
Examples:
Courses/Submit Assignment = placeholder tab the first time, second time works fine.
Courses/Print cover sheet = redirect to main page second time selected works fine.
Courses/Find a testing Center = placeholder tab the first time, second time works fine.
![placeholder 2](https://cloud.githubusercontent.com/assets/20323154/16625362/6fc43b04-4361-11e6-82c2-f1ed84873e8e.PNG)
![placeholder](https://cloud.githubusercontent.com/assets/20323154/16625363/6fc4ccae-4361-11e6-9e37-f75df1f55497.PNG)

**Comment by mcshinsky90** [comment]
Also happens to Support/submit Assignment

**Comment by luke80** [comment]
Your browser had a cache of the old files. Going there refreshed them and picked up the new files, which are already fixed! yey!
