### ISSUE TITLE
Purchase Order Form Links

### ISSUE THREAD

**Issue by mcshinsky90** [BYU-IS-Media/independent_study#93]
1. There are 2 identical links on the left side of the page that lead to the same forms. Financial Aid/Purchase Orders

2. All of the actual links to PO forms all redirect to the home page rather then the forms needed. Financial Aid/Purchase Orders/Purchase Order Forms

3 Under the Purchase order FAQ's page all of the title links look like they should redirect to more information but just redirect to the top of the page. Financial Aid/Purchase Orders/Purchase Order FAQ's

4.Links under Financial Aid/Purchase Orders. All of the ones that say "click here to read more" as well as "Submit forms by E-mail instructions" and "Organization Application for Credit" all lead to the home page and the three at the bottom of the page "What is a purchase order?", "How do I use a purchase order?" and "How do I read my monthly Invoice?" Redirect to the top of the page.

![po links 2](https://cloud.githubusercontent.com/assets/20323154/16625551/5a15edce-4362-11e6-9979-d7851750267a.PNG)
![po links](https://cloud.githubusercontent.com/assets/20323154/16625550/5a151642-4362-11e6-894a-3dbfa5bb96b3.PNG)

**Comment by luke80** [comment]
The view needed to have "query parameters" turned on, as well as "remove duplicates"

Also please include the "path" in your screenshots.
