### ISSUE TITLE
FERPA Link

### ISSUE THREAD

**Issue by megmcclell** [BYU-IS-Media/independent_study#98]
When you go to the privacy section through the Courses tab>Course policies>Privacy and click on the Ferpa Form link, it directs you back to the main is.byu.edu page. If you just go directly through About tab>Privacy then that link works.
![ferpa link](https://cloud.githubusercontent.com/assets/19712366/17033336/f38b353e-4f3a-11e6-8d81-cef48cfb3c51.PNG)
![ferpa link 2](https://cloud.githubusercontent.com/assets/19712366/17033339/f6a4c73a-4f3a-11e6-95e3-1eb1cf199ac5.PNG)

**Comment by nicoleku** [comment]
Fixed it, it's now pointing to isreg site.
