### ISSUE TITLE
New University Scholarship Form

### ISSUE THREAD

**Issue by aaronmoody** [BYU-IS-Media/independent_study#99]
The university scholarship application form needs to be updated.  Please attach this PDF instead of the one that is currently on the site under the financial aid tab.  Thanks!

[NEW2 University Scholarship Application.pdf](https://github.com/BYU-IS-Media/independent_study/files/391300/NEW2.University.Scholarship.Application.pdf)

**Comment by luke80** [comment]
I believe this was fixed already when this issue was posted. :)

**Comment by aaronmoody** [comment]
Sorry if there was a misunderstanding.  The link works just fine, nothing needs to be fixed.  It's that the form has been updated and we need to attach this new form in place of the one that is currently on the site.  I just double-checked and the form that is still there is the old one.

**Comment by luke80** [comment]
Oh! I missed the difference. I'll help marketing fix this.

**Comment by brycemac** [comment]
This is fixed
